# Generated by Django 5.2.11 on 2026-02-25 02:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('completed', '完成'), ('inquiry', '询单'), ('quoted', '报价')], default='inquiry', max_length=20)),
                ('file', models.FileField(upload_to='quotations/')),
            ],
        ),
    ]
