# Generated by Django 6.0.2 on 2026-02-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotation",
            name="file",
        ),
        migrations.AddField(
            model_name="quotation",
            name="folder_path",
            field=models.CharField(
                default="/quotations", max_length=500, verbose_name="文件夹路径"
            ),
        ),
    ]
